version: "3"

services:
  web-mvc:
    image: marcusfcbarbosa/nerdstore-web-mvc-ecommerce:latest
    container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    ports:
      - "5001:5001"
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
  
  api-catalogo:
    image: marcusfcbarbosa/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
        context:  ../src
        dockerfile: ./services/NSE.Catalogo.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:44307

